language: node_js
sudo: required

jobs:
  include:
    - stage: release
      # script: skip
      deploy:
        if: branch = master
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
